version: '3.7'
services:
  algo_back:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: algo
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - /Users/study/algoQnA/back/db/question.sql
