version: '3.8'
services:
  dailyalgo_back:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dailyalgo_back
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - SERVER_URL=${SERVER_URL}
      - DB_HOST_WRITE=${DB_HOST_WRITE}
      - DB_HOST_READ=${DB_HOST_READ}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_KAKAO_CLIENT_ID=${OAUTH_KAKAO_CLIENT_ID}
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf