version: '3.7'
services:
  dailyalgo_back:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: algo
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: nodecrew
      MYSQL_DATABASE: daily_algo
